<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2018-01-06 17:16:41
 *	Namespace App\Http\Controllers\Auth
 */

namespace App\Http\Controllers\Auth;

use IceTea\Http\Controller;

class LoginController extends Controller
{
	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	return view('auth/login');
    }
}
