<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2018-01-06 21:20:39
 *	Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use IceTea\Http\Controller;
use IceTea\Session\SessionHandler as S;

class ClientAreaController extends Controller
{
	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	$a = S::get('user');
    	return view('clientarea', ['name' => $a['username']]);
    }
}
