<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-16 18:40:06
 *	Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use IceTea\Http\Controller;

class ElfinderController extends Controller
{
	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	return view('elfinder');
    }

    public function connector()
    {
    	require basepath('init/elfinder_connector.php');
    }
}
