<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2018-01-06 16:56:11
 *	Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use IceTea\Http\Controller;
use IceTea\Session\SessionHandler as S;

class ElfinderController extends Controller
{
	public function __construct()
	{
		parent::__construct();
	}

    public function connector()
    {
        if ($u = S::get('user')) {
            
            $docroot = $u['document_root'];
            $trash = "{$docroot}/.trash";
            is_dir($trash) or mkdir($trash);
            require basepath('elfinder/php/connector.minimal.php');
        } else {
            header("location:".route('login'));
        }
    }

    public function index()
    {
    	return view('elfinder');
    }
}
