<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2018-01-06 16:48:51
 *	Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use IceTea\Http\Controller;

class IndexController extends Controller
{
	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	return view('index');
    }
}
