<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2018-01-06 17:41:59
 *	Namespace App\Models
 */

namespace App\Models;

use IceTea\Database\DB;
use IceTea\Support\Model;

class Auth extends Model
{
	public function __construct()
	{
		parent::__construct();
	}

	public static function login($username, $password)
	{
		if (file_exists($file = basepath("storage/app/hot/accounts/{$username}"))) {
			$a = json_decode(file_get_contents($file), true);
			if (isset($a['username'], $a['password'], $a['document_root'], $a['main_domain'])) {
				if ($username === $a['username'] and $password === $a['password']) {
					return $a;
				}
			}
		}
		return false;
	}
}
